### ISSUE TITLE
Reduce console spew in processor.test.ts

### ISSUE THREAD

**Issue by MikeHopcroft** [microsoft/secure-data-sandbox#8]
~~~
Error: simulated failure
    at D:\git\data-contest-toolkit\build\test\unit\queue\processor.test.js:68:19
    at QueueProcessor.processBatch (D:\git\data-contest-toolkit\build\src\queue\processor.js:44:23)
Error: simulated failure
    at D:\git\data-contest-toolkit\build\test\unit\queue\processor.test.js:68:19
    at QueueProcessor.processBatch (D:\git\data-contest-toolkit\build\src\queue\processor.js:44:23)
Error: simulated failure
    at D:\git\data-contest-toolkit\build\test\unit\queue\processor.test.js:68:19
    at QueueProcessor.processBatch (D:\git\data-contest-toolkit\build\src\queue\processor.js:44:23)
could not process {"value":"msg 1","dequeueCount":4}
~~~

**Comment by noelbundick** [comment]
These are warnings / errors being written to STDERR. You can execute just tests & suppress these messages via `npm run test 2>/dev/null`

Long-term, this will be resolved when we wire up a proper observability solution via AppInsights / etc.
